[package]
name = "La Guerra Impresionante de Condenación Final"
version = "0.1.0"
authors = ["Joel W Kall"]

[[bin]]
name = "lgidcf"

[dependencies]
piston = "*"
piston2d-graphics = "*"
piston_window = "*"
piston2d-gfx_graphics = "*"
gfx_device_gl = "*"
rand = "*"
rustc-serialize = "0.3.19"